---
# The specific version that we aim at installing.
# If we wanted to get whatever is the latest not 
# marked as a release candidate we could instead
# not specify a version but simply `docker-ce`.
docker_version: '17.09.0~ce-0~ubuntu'

# The release channel to look for packages.
# If your curious about what are the channels and which
# versions do they have, head to
# https://download.docker.com/linux/ubuntu/dists/zesty/ (or
# any other distro you want).
docker_apt_release_channel: 'stable'

# The url of the apt repository.
# Here we're picking the values from the knowledge
# that ansible already took from the system. This way
# we can make fewer changes in this code when changing
# from one distro to another.
# Note that there's a compatility matrix but in general
# new versions of Ubuntu are well covered.
docker_apt_repository: 'deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}'

# List of users that we want to add to the
# docker group. As mentioned, by adding them to
# the `docker` group they can access the unix socket
# that docker places at `/var/run/docker.sock` (by default)
# which the docker CLI uses to communicate with
# the docker daemon.
docker_group_members: 
  - 'ubuntu'
